os: linux
language: c
dist: xenial
script:
  - git ls-files build/src/ | xargs clang-format  && git diff --exit-code
  - git ls-files build/test/ | xargs clang-format  && git diff --exit-code
  - make
  - make test
  - make testing
compiler:
- gcc
